site_name: Introdução ao Projeto de Circuitos Digitais utilizando FPGA
site_author: Rodolfo Azevedo
site_description: Introdução ao Projeto de Circuitos Digitais utilizando FPGA
repo_name: FPGA
repo_url: https://github.com/rjazevedo/FPGA
copyright: CC BY-SA 4.0 - Rodolfo Azevedo
theme: 
  name: material
  highlightjs: true
  language: pt-BR
  features:
    - content.code.copy
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - toc.integrate
    - navigation.top
    - navigation.footer
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      use_pygments: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom  
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - tables
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/@rjazevedo
    - icon: fontawesome/brands/github
      link: https://github.com/rjazevedo
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/rjazevedo
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/rjazevedo
  palette: 
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
plugins:
  - search
  - mermaid2
  # - pdf-export:
  #     enabled_if_env: ENABLE_PDF_EXPORT
  # - table-reader
  # - autolinks
nav:
  - Apresentação : index.md
  - Circuitos Lógicos: 
    - Sistemas De Numeração: SistemasDeNumeracao.md
    - Circuitos Lógicos: CircuitosLogicos.md
    - Portas Lógicas: PortasLogicas.md
    - Circuitos Combinacionais: CircuitosCombinacionais.md
    - Circuitos Sequenciais: CircuitosSequenciais.md
    - Máquinas de Estado: MaquinasDeEstado.md
    - Memórias: Memorias.md
  - Verilog: 
    - Noções Básicas de Verilog: verilogNocoesBasicas.md
    - Primeiro circuito: verilogPrimeiroCircuito.md
    - Como Simular: verilogComoSimular.md
    - Circuito Combinacional: verilogCircuitoCombinacional.md
    - Display de 7 Segmentos: verilogDisplay7Segmentos.md
    - Circuito Sequencial: verilogCircuitoSequencial.md
    - Máquina de Estados: verilogMaquinasDeEstados.md
  - Avançado: 
    - Componentes externos
  - Atividades:
    - Circuitos Sequenciais:
      - 000 - Começando do inicio: laboratorios/000-blink.md
      - 001 - Contador de LEDs: laboratorios/001-led_counter.md
      - 002 - Deslocamento de LEDs: laboratorios/002-led_shifter.md
    - Sinais externos:
      - 003 - Botão: laboratorios/003-button.md
    - Decodificadores:
      - 004 - Códigos de correção de erro: laboratorios/004-hamming_code.md
      - 005 - Display de 7 Segmentos: laboratorios/005-7_segment.md
      - 006 - Relógio Simples: laboratorios/006-simple_clock.md
    - Maquinas de Estado:
      - 007 - Modos de Botão: laboratorios/007-button_modes.md
      - 008 - Semáforo: laboratorios/008-semaphore.md
      - 009 - Semáforo com Display de 7 Segmentos: laboratorios/009-7_segment_semaphore.md
    - Operações Aritméticas:
      - 010 - Construindo uma unidade Logica Aritmética: laboratorios/010-alu.md
      - 011 - Calculadora: laboratorios/011-calculator.md
    - Memória:
      - 012 - Memória: laboratorios/012-memory.md
    - Modulação:
      - 013 - PWM: laboratorios/013-pwm.md
      - 014 - Servo Motor: laboratorios/014-servo.md
      - 015 - Construindo um Reprodutor de Músicas: laboratorios/015-simple_music_player.md
    - Comunicação Serial:
      - 016 - Serdes: laboratorios/016-serdes.md
      - 017 - SPI: laboratorios/017-spi.md
      - 018 - Acelerômetro SPI: laboratorios/018-spi_accelerometer.md
      - 019 - Cartão SD SPI: laboratorios/019-spi_sdcard.md
      - 020 - Display SPI: laboratorios/020-spi_display.md
      - 021 - I2C: laboratorios/021-i2c.md
      - 022 - Acelerômetro I2C: laboratorios/022-i2c_accelerometer.md
      - 023 - Sensor de Temperatura I2C: laboratorios/023-i2c_temperature_sensor.md
      - 024 - Display I2C: laboratorios/024-i2c_display.md
      - 025 - UART: laboratorios/025-uart.md
      - 026 - GPS UART: laboratorios/026-uart_gps.md
    - Manipulanção de Frequência:
      - 027 - PLL: laboratorios/027-pll.md
      - 028 - VGA: laboratorios/028-vga.md
      - 029 - Pong: laboratorios/029-pong.md
      - 030 - HDMI: laboratorios/030-hdmi.md
      - 031 - Câmera: laboratorios/031-camera.md
      - 032 - Detector de Mãos: laboratorios/032-hand_detector.md
    - Processadores:
      - 033 - Utilizando um Softcore RISC-V: laboratorios/033-using_softcore.md
      - 034 - Tornando GPIO um Periférico: laboratorios/034-making_gpio_peripheral.md
      - 035 - Inicializando Linux: laboratorios/035-booting_linux.md
  - Guias:
    - Instalação: guias/instalacao.md